### ISSUE TITLE
Better home page?

### ISSUE THREAD

**Issue by pcav** [gis4developer/QGIS#2]
I'm not sure having a home page in Facebook is a very good idea. No other plugin does so, and it requires a (very non standard) FB account.
I'd suggest to use this repo as a home page; in the README you can add any link to relevant pages that may be useful to users, including if you really want a FB page.
How does it sound?
Thanks for understanding.

**Comment by gis4developer** [comment]
Thank for suggestion.
Now, I have offical home page on FB (https://www.facebook.com/GIS4Dev-101058764633058/)
or you can found it in https://github.com/gis4developer/QGIS/blob/master/README.md

**Comment by pcav** [comment]
Please check: in both the https://plugins.qgis.org/plugins/tmd/ page and readme still the FB home page is listed.
Please reopen this ticket,
Thanks.

**Comment by gis4developer** [comment]
> Please check: in both the https://plugins.qgis.org/plugins/tmd/ page and readme still the FB home page is listed.
> Please reopen this ticket,
> Thanks.

Fixed.

**Comment by pcav** [comment]
Still not fixed, please check.

**Comment by gis4developer** [comment]
@pcav 
In https://plugins.qgis.org/plugins/tmd/. I provide a facebook fanpage and facebook group for discussion about QGIS Plugin (Figure 1).
![2020-01-13_16-09-08](https://user-images.githubusercontent.com/58878436/72243706-30de9100-361f-11ea-8465-616803517486.jpg)
Figure 1


This is a GIS4Dev fanpage, It talks about QGIS ArcGIS GeoServer Google Earth Engine etc. If user want to discuss about QGIS plugin, They click button (In red rectangle) to go to QGIS Plugin Group (Figure 2)
![2020-01-13_15-55-25](https://user-images.githubusercontent.com/58878436/72243436-88c8c800-361e-11ea-8f38-79fb2302ed3d.jpg)
Figure 2


This is a facebook QGIS Plugin group (Figure 3)
![2020-01-13_15-56-43](https://user-images.githubusercontent.com/58878436/72243866-8dda4700-361f-11ea-93f8-0de8d1fabd48.jpg)
Figure 3

If this is not correct way please tell me more detail.

**Comment by pcav** [comment]
I'd recommend not having a FB page as home page: not everybody has a FB account, especially for professional purposes.
You can use this repo as HP, and add there a link to your FB page is you wish.

**Comment by gis4developer** [comment]
@pcav 
My home page look like this, It's OK or not ?
![2020-01-14_9-56-44](https://user-images.githubusercontent.com/58878436/72310640-cd06a780-36b4-11ea-98bd-5cf05ba0eecf.jpg)

**Comment by pcav** [comment]
Sorry, I think there is a misunderstanding here:
* https://plugins.qgis.org/plugins/tmd/ still has the FB page
* as a code repo better https://github.com/gis4developer/QGIS/ than https://github.com/gis4developer/QGIS/tree/master/tmd
* the directory structure is not optimal: please remove the README in the top directory and move all files up one level.
Cheers.

**Comment by gis4developer** [comment]
@pcav 
1. I removed the FB page from https://plugins.qgis.org/plugins/tmd/
![2020-01-15_10-04-21](https://user-images.githubusercontent.com/58878436/72401589-06a3e500-377f-11ea-86f4-f2c00a128739.jpg)

2. I changed code repository from https://github.com/gis4developer/QGIS/tree/master/tmd to  https://github.com/gis4developer/QGIS/
![2020-01-15_10-05-36](https://user-images.githubusercontent.com/58878436/72401631-25a27700-377f-11ea-921c-7eb9013653bd.jpg)

3. I optimized the directory structure, Now It has only one level.
![2020-01-15_10-06-27](https://user-images.githubusercontent.com/58878436/72401778-a5304600-377f-11ea-8901-23d7193387bd.jpg)

**Comment by pcav** [comment]
Thanks
